packages:
  - packages/*

allowBuilds:
  '@firebase/util': set this to true or false
  '@tsparticles/engine': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  spawn-sync: set this to true or false
  vue-demi: set this to true or false

onlyBuiltDependencies:
  - '@firebase/util'
  - '@tsparticles/engine'
  - esbuild
  - protobufjs
  - spawn-sync
  - vue-demi
