packages:
  - packages/*
  - apps/*

allowBuilds:
  '@firebase/util': true
  '@tsparticles/engine': true
  esbuild: true
  protobufjs: true
  spawn-sync: true
  vue-demi: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@tsparticles/engine'
  - esbuild
  - protobufjs
  - spawn-sync
  - vue-demi
